title: Alya Vienneau-Lee # your name (or website title) here
logo: "images/portfolio_image.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello, and welcome to my portfolio. Here is where you can find the latest samples of my written works. 
  <br><br>
  On the right hand side of this page is a demo game made via Twine, which will open easily in your browser. Below that are other samples, whose titles and explanations should prove self-explanatory.
  <br><br>
  <a href="https://www.linkedin.com/in/alya-v-l/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
